---

- import_tasks: agent.yml
  tags:
    - consul

- import_tasks: exporter.yml
  when: consul_exporter_enabled|default(false)
  tags:
    - consul

- import_tasks: services.yml
  when: consul_services|default([])
  tags:
    - consul
