---

- name: Assemble consul service config
  template: src=services.json.j2 dest="{{ consul_conf_dir }}/{{ item.name }}.json" mode=0644
  vars:
    entries: "{{ item.entries }}"
  with_items: "{{ services }}"
  notify: reload consul
