---

traefik_enabled: false

traefik_service_dir: /opt/services/traefik
traefik_certs_dir: "{{ traefik_service_dir }}/certs"
traefik_conf_dir: "{{ traefik_service_dir }}/conf.d"

traefik_consul_provider: false
traefik_consul_provider_host: localhost
traefik_consul_provider_port: 8500
traefik_consul_provider_constraints: ''

traefik_docker_provider: false

traefik_file_provider: true
traefik_file_provider_dir: /etc/traefik/conf.d

traefik_access_log_enabled: false

traefik_image: traefik:latest

traefik_container_name: traefik
traefik_container_hostname: "{{ ansible_hostname }}"
traefik_container_labels: {}
traefik_container_dns_servers: []
traefik_container_log_driver: syslog
traefik_container_log_options:
  syslog-address: unixgram:///dev/log
  tag: traefik
traefik_container_networks: []
traefik_container_restart_policy: always
traefik_container_ports:
  - "{{ traefik_entry_points.web.host }}:{{ traefik_entry_points.web.external_port }}:{{ traefik_entry_points.web.internal_port }}"
  - "{{ traefik_entry_points.websecure.host }}:{{ traefik_entry_points.websecure.external_port }}:{{ traefik_entry_points.websecure.internal_port }}"
  - "{{ traefik_entry_points.exporter.host }}:{{ traefik_entry_points.exporter.external_port }}:{{ traefik_entry_points.exporter.internal_port }}"

traefik_entry_points:
  web:
    name: web
    host: localhost
    internal_port: 80
    external_port: 80
  websecure:
    name: websecure
    host: localhost
    internal_port: 443
    external_port: 443
  exporter:
    name: exporter
    host: localhost
    internal_port: 8800
    external_port: 8800

traefik_basic_auth: []

traefik_letsencrypt: false
traefik_letsencrypt_email: ''
traefik_letsencrypt_resolver: acmeresolver

traefik_service:
  name: "traefik-{{ traefik_entry_points.web.name }}"
  host: "{{ traefik_entry_points.web.host }}"
  port: "{{ traefik_entry_points.web.external_port }}"
  tags:
    - "{{ tier }}"
  meta:
    hostname: "{{ ansible_hostname }}"
    tier: "{{ tier }}"

traefik_secure_service:
  name: "traefik-{{ traefik_entry_points.websecure.name }}"
  host: "{{ traefik_entry_points.websecure.host }}"
  port: "{{ traefik_entry_points.websecure.external_port }}"
  tags:
    - "{{ tier }}"
  meta:
    hostname: "{{ ansible_hostname }}"
    tier: "{{ tier }}"

traefik_exporter_service:
  name: "traefik-{{ traefik_entry_points.exporter.name }}"
  host: "{{ traefik_entry_points.exporter.host }}"
  port: "{{ traefik_entry_points.exporter.external_port }}"
  tags:
    - "{{ tier }}"
  meta:
    hostname: "{{ ansible_hostname }}"
    tier: "{{ tier }}"
