---

- name: Prepare folders
  file: path={{ loki_service_dir }} state=directory mode=0755

- name: Assemble config
  template: src=promtail.yml.j2 dest={{ loki_service_dir }}/promtail.yml mode=0644
  notify: restart promtail

- name: Pull image
  docker_image: name={{ promtail_image }} source=pull

- name: Create volume
  docker_volume: name={{ promtail_volume }}

- name: Run container
  docker_container:
    name: "{{ promtail_container_name }}"
    image: "{{ promtail_image }}"
    command: -config.file=/etc/promtail/config.yml
    dns_servers: "{{ promtail_container_dns_servers }}"
    labels: "{{ promtail_container_labels }}"
    log_driver: "{{ promtail_container_log_driver }}"
    log_options: "{{ promtail_container_log_options }}"
    networks: "{{ promtail_container_networks|default([]) }}"
    published_ports:
      - "{{ promtail_host }}:{{ promtail_port }}:9080"
      - "{{ promtail_syslog_host }}:{{ promtail_syslog_port }}:1514"
    restart_policy: "{{ prometheus_container_restart_policy }}"
    volumes:
      - "{{ promtail_volume }}:{{ promtail_volume_dir }}"
      - "{{ loki_service_dir }}/promtail.yml:/etc/promtail/config.yml"
      - /var/log:/var/log

- name: Assemble syslog config
  template: src=syslog.conf.j2 dest=/etc/rsyslog.d/promtail.conf mode=0644
  notify: restart syslog
