---

- name: Pull cadvisor exporter image
  docker_image: name={{ cadvisor_image }} source=pull

- name: Run cadvisor exporter container
  docker_container:
    name: "{{ cadvisor_container_name }}"
    image: "{{ cadvisor_image }}"
    command: -logtostderr -docker_only
    log_driver: "{{ cadvisor_container_log_driver }}"
    log_options: "{{ cadvisor_container_log_options }}"
    published_ports:
      - "{{ cadvisor_host }}:{{ cadvisor_port }}:8080"
    restart_policy: "{{ cadvisor_container_restart_policy }}"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
